### ISSUE TITLE
Add "async function" to function 

### ISSUE THREAD

**Issue by Charchika23** [nguyenngoclongdev/step-definition-generator#24]
Thanks for this plugin. it is helpful to create unique step defs.
I am using playwright + typescript + cucumber framework and wanted to request if ""async function" can be added to function definition when above framework combination is used.

Currently step def generated is:
Then(`I should see text {string}`, (arg0: string) => {
    // [Then] Describes the expected outcome or result of the scenario.
});

Requested step def generation:
 Then(`I should see text {string}`, **async function** (arg0: string) => {
    // [Then] Describes the expected outcome or result of the scenario.
});

Thanks!

**Comment by nguyenngoclongdev** [comment]
@Charchika23 You can enable the setting below to generate an async function.
![image](https://github.com/user-attachments/assets/ad02165c-9de3-461b-aa76-d3d1b2c131df)
